name: CommandPointsEssentials
main: pgDev.bukkit.CommandPointsEssentials.CommandPointsEssentials
version: 0.5
author: PG Dev Team
authors: [Devil Boy, Blackside921]
description: Essential commands that any player can execute with the necessary amount of commandpoints.
softdepend: [CommandPoints, mcMMO]

commands:
   chelp:
      description: Check what commands are available to you.
      usage: /<command>
   creative:
      description: Easily switch to creative mode.
      usage: /<command>
   survival:
      description: Easily switch to survival mode.
      usage: /<command>
   ctp:
      description: A simpler version of the teleport command.
      usage: /<command> <otherplayer>
   cgive:
      description: A simpler version of the give command.
      usage: /<command> <item> [amount]
   i:
      description: A short form of the cgive command.
      usage: /<command> <item> [amount]
   day:
      description: Makes it daytime.
      usage: /<command>
   night:
      description: Makes it nighttime.
      usage: /<command>
   spawn:
      description: Teleport to the spawn.
      usage: /<command>
   bed:
      description: Teleport to your last sleep location.
      usage: /<command>
   accept:
      description: Accept a teleport request.
      usage: /<command>
   caccept:
      description: An alternate for the accept command.
      usage: /<command>
   reject:
      description: Reject a teleport request.
      usage: /<command>
   creject:
      description: An alternate for the reject command.
      usage: /<command>
   buyexp:
      description: Purchase EXP levels.
      usage: /<command> [amount]
   back:
      description: Teleport to death location.
      usage: /<command>
      
permissions:
    CPE.*:
        default: op
        description: Gives access to the cpessentials commands.
    CPE.chelp:
        default: true
        description: Is allowed to see what commands are available.
        command: "/chelp"
    CPE.creative:
        default: op
        description: Can switch to creative mode.
        command: "/creative"
    CPE.survival:
        default: op
        description: Can switch to survival mode.
        command: "/survival"
    CPE.cgive:
        default: op
        description: Can give themselves items.
        command: "/cgive"
    CPE.ctp:
        default: true
        description: Can use points to teleport.
        command: "/ctp"
    CPE.ctp.free:
        default: op
        description: Can use the ctp command for free.
    CPE.day:
        default: true
        description: Can use points to change time to day.
        command: "/day"
    CPE.day.free:
        default: op
        description: Can use the day command for free.
    CPE.night:
        default: true
        description: Can use points to change time to night.
        command: "/night"
    CPE.night.free:
        default: op
        description: Can use the night command for free.
    CPE.spawn:
        default: true
        description: Can teleport to the spawn.
        command: "/spawn"
    CPE.spawn.free:
        default: op
        description: Can teleport to the spawn for free.
    CPE.bed:
        default: true
        description: Can teleport to last bed slept in.
        command: "/bed"
    CPE.bed.free:
        default: op
        description: Can teleport to bed for free.
    CPE.buyexp:
        default: true
        description: Can buy EXP levels.
        command: "/buyexp"
    CPE.buyexp.free:
        default: op
        description: Can get EXP levels for free.
    CPE.back:
        default: true
        description: Can teleport to death location.
    CPE.back.free:
        default: op
        description: Can teleport to death location for free.