name: CommandPointsEssentials
main: pgDev.bukkit.CommandPointsEssentials.CommandPointsEssentials
version: 0.1
author: Devil Boy
description: Essential commands that any player can execute with the necessary amount of commandpoints.
softdepend: [CommandPoints]

commands:
   creative:
      description: Easily switch to creative mode.
      usage: /<command>
   survival:
      description: Easily switch to survival mode.
      usage: /<command>
   ctp:
      description: A simpler version of the teleport command.
      usage: /<command> <otherplayer>
   cgive:
      description: A simpler version of the give command.
      usage: /<command> <item> [amount]
   i:
      description: A short form of the cgive command.
      usage: /<command> <item> [amount]
   day:
      description: Makes it daytime.
      usage: /<command>
   night:
      description: Makes it nighttime.
      usage: /<command>
      
permissions:
    CPE.*:
        default: op
        description: Gives access to the essential admin commands.
        children:
            CPE.creative: true
            CPE.survival: true
            CPE.cgive: true
            CPE.ctp: true
            CPE.day: true
            CPE.night: true
    CPE.creative:
        default: op
        description: Can switch to creative mode.
        command: "/creative"
    CPE.survival:
        default: op
        description: Can switch to survival mode.
        command: "/survival"
    CPE.cgive:
        default: op
        description: Can give themselves items.
        command: "/cgive"
    CPE.ctp:
        default: true
        description: Can use points to teleport.
        command: "/ctp"
    CPE.ctp.free:
        default: op
        description: Can use the ctp command for free.
    CPE.day:
        default: true
        description: Can use points to change time to day.
        command: "/day"
    CPE.day.free:
        default: op
        description: Can use the day command for free.
    CPE.night:
        default: true
        description: Can use points to change time to night.
        command: "/night"
    CPE.night.free:
        default: op
        description: Can use the night command for free.